/**
 * AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
 *
 * Generated by: npm run process_controller_defs
 * Source captures: ps5.json
 */

import profile0 from './profiles/054c-0ce6.js';

export const controllerProfiles = {
  '054c-0ce6': profile0,
};

/**
 * Return all generated controller profiles.
 */
export function getControllerProfiles() {
  return controllerProfiles;
}

/**
 * Resolve the most specific profile by (vendorId, productId).
 * Falls back to first profile with matching vendorId if exact product is unknown.
 */
export function findControllerProfile(vendorId, productId) {
  const v = typeof vendorId === "string" ? vendorId.toLowerCase() : null;
  const p = typeof productId === "string" ? productId.toLowerCase() : null;
  if (!v) return null;

  const exactKey = p ? `${v}-${p}` : null;
  if (exactKey && controllerProfiles[exactKey]) return controllerProfiles[exactKey];

  let vendorFallback = null;
  for (const profile of Object.values(controllerProfiles)) {
    if (!profile || profile.vendorId !== v) continue;
    if (!vendorFallback) vendorFallback = profile;
    if (p && profile.productId === p) return profile;
  }
  return vendorFallback;
}

/**
 * Parse VID/PID from a browser gamepad id string and return a matching profile if present.
 */
export function findControllerProfileByGamepadId(gamepadId) {
  if (!gamepadId || typeof gamepadId !== "string") return null;
  const m = gamepadId.match(/^([0-9a-fA-F]{4})-([0-9a-fA-F]{4})-/);
  if (!m) return null;
  return findControllerProfile(m[1], m[2]);
}
